swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "HrvvI Me"
  contact:
    email: "sbl1996@126.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/api"
host: "localhost:5000"
tags:
- name: "post"
  description: "Blog posts"
schemes:
- "http"
paths:
  /posts:
    get:
      tags:
      - "post"
      summary: "Get all posts"
      description: "Get all posts"
      parameters:
      - name: "year"
        in: "query"
        required: false
        type: "integer"
      - name: "q"
        in: "query"
        description: "Keyword"
        required: false
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Post"
        400:
          description: "Invalid year"
    post:
      tags:
      - "post"
      summary: "Add a new post"
      description: ""
      operationId: "createPost"
      parameters:
      - in: "body"
        name: "body"
        description: "Post object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/Post"
      responses:
        201:
          description: ""
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                description: "Id of added post"
        400:
          description: "Invalid input"
    patch:
      tags:
      - "post"
      summary: "Update an existing post"
      description: ""
      operationId: "updatePost"
      parameters:
      - in: "body"
        name: "body"
        description: "Post object that needs to be updated"
        required: true
        schema:
          $ref: "#/definitions/Post"
      responses:
        200:
          description: "Updated"
        400:
          description: "Invalid ID supplied"
  /posts/{postId}:
    get:
      tags:
      - "post"
      summary: "Find post by ID"
      description: "Returns a single post"
      operationId: "getPostById"
      parameters:
      - name: "postId"
        in: "path"
        description: "ID of post to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Post"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Post not found"
    delete:
      tags:
      - "post"
      summary: "Delete a Post"
      description: ""
      operationId: "deletePost"
      parameters:
      - name: "postId"
        in: "path"
        description: "Post id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Deleted"
        400:
          description: "Invalid ID supplied"
definitions:
  Post:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      title:
        type: "string"
      content:
        type: "string"
      date:
        type: "string"
        format: "date-time"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"